config/routes.rb
Rails.application.routes.draw do

    root to: 'home#index'
    devise_for :users
    resources :users
    get 'home' => 'home#index'
    get 'auth' => 'instagram#connect'
    get 'callback' => 'instagram#callback'
    get 'users/:id/notfollowback' => 'users#not_follow_back'
    get 'users/:id/stopfollow' => 'users#stop_follow'
    get 'users/:id/pokemon' => 'users#pokemon'
    get 'users/:id/tags' => 'users#tags'

		get 'user/:id/tags' => "insta_tags#user_tags"
		get '/tags' => "insta_tags#apriori"
    post 'instagram/unfollow' => 'instagram#un_follow'
    post 'instagram/follow' => 'instagram#follow'

end

app/models/inst_relation.rb
class InstRelation < ActiveRecord::Base
  belongs_to :follower, class_name: 'InstaUser'
  belongs_to :followed, class_name: 'InstaUser'
  validates :followed_id, presence: true
  validates :follower_id, presence: true
end

app/models/inst_tag.rb
class InstTag < ActiveRecord::Base
  require 'instagram'

  has_many :tag_relations
  has_many :insta_users, through: :tag_relations

  has_many :photo_tags
  has_many :user_photos, through: :photo_tags

  def self.addTag(user, tag)
    tag_n = InstTag.find_or_create_by(name: tag)
    tag_r = TagRelation.find_or_create_by(insta_user_id: user.id,
                                         inst_tag_id: tag_n.id)
    tag_r.increment(:counter, by = 1)
    tag_r.save
  end
end

app/models/inst_token.rb
class InstToken < ActiveRecord::Base
  belongs_to :user
end

app/models/insta_user.rb
class InstaUser < ActiveRecord::Base
  validates :username, uniqueness: true
  validates :username, :ins_id, presence: true
  has_many :tag_relations
  has_many :inst_tags, through: :tag_relations
  has_many :active_relationships, class_name: 'InstRelation',
       foreign_key: :follower_id,
       dependent: :destroy
  has_many :passive_relationships, class_name: 'InstRelation',
       foreign_key: :followed_id,
       dependent: :destroy
  has_many :followering, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :was_active_relationships, class_name: 'WasRelation',
       foreign_key: :follower_id,
       dependent: :destroy
  has_many :was_passive_relationships, class_name: 'WasRelation',
       foreign_key: :followed_id,
       dependent: :destroy
  has_many :was_followering, through: :was_active_relationships, source: :followed
  has_many :was_followers, through: :was_passive_relationships, source: :follower

  has_many :user_photo_relations
  has_many :user_photos, through: :user_photo_relations

  def follow(insta_user)
    was_active_relationships.find_by(followed_id: insta_user.id).destroy if
        was_followering.include?(insta_user)
    active_relationships.create(followed_id: insta_user.id)
  end

  def unfollow(insta_user)
    active_relationships.find_by(followed_id: insta_user.id).destroy
    was_active_relationships.create(followed_id: insta_user.id)
  end

  def self.add(inst_user)
    if InstaUser.find_by(username: inst_user.username).nil?
      InstaUser.create(ins_id: inst_user.id, username: inst_user.username)
    end
  end
end

app/models/photo_tag.rb
class PhotoTag < ActiveRecord::Base
	belongs_to :inst_tag
	belongs_to :user_photop
end

app/models/tag_relation.rb
class TagRelation < ActiveRecord::Base
  belongs_to :insta_user
  belongs_to :inst_tag
  has_one :inst_tag
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :inst_token
  has_one :insta_user
  scope :active_user, -> { where(have_authorization: true).order('created_at desc') }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
     :recoverable, :rememberable, :trackable, :validatable
end

app/models/user_photo.rb
class UserPhoto < ActiveRecord::Base
	has_one :user_photo_relation
	has_one :insta_user, through: :user_photo_relations
	has_many :photo_tags
	has_many :inst_tags, through: :photo_tags
end

app/models/user_photo_relation.rb
class UserPhotoRelation < ActiveRecord::Base
	belongs_to :insta_user
	belongs_to :user_photo
end

app/models/was_relation.rb
class WasRelation < ActiveRecord::Base
  belongs_to :follower, class_name: 'InstaUser'
  belongs_to :followed, class_name: 'InstaUser'
  validates :followed_id, presence: true
  validates :follower_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery prepend: true
  before_action :authenticate_user!
  #force_ssl
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_action :check_auth

  def index

  end

  def check_auth
    if user_signed_in? && current_user.have_authorization?
      redirect_to current_user
    end
  end
end

app/controllers/insta_tags_controller.rb
class InstaTagsController < ApplicationController

	def user_tags
		id = params[:id]
		ins = InstaUser.find(id)
		client = Instagram.client(access_token:
																	 current_user.inst_token.access_token)
		MediaCounter.update(client)
		media = client.user_recent_media(ins.ins_id)
		TakeTagFromPhotos.new.call(media,ins)
		ValuablePhoto.call(media,30,ins)
		@tags = InstTag.joins(:tag_relations).where("tag_relations.insta_user_id= #{id}"
		).order("tag_relations.counter desc").limit(20)
	end

	def apriori
		@list = DateToMachineLerning.convert
		@res = MachineLearning.apriori(@list,10,20)
	end

end

app/controllers/instagram_controller.rb
# Request to Instagram API
class InstagramController < ApplicationController
  require 'instagram'

  before_action :take_data, only: [:un_follow, :follow]
  
  def connect
    redirect_to Instagram.authorize_url(
      redirect_uri: CALLBACK_URL, scope:
        'follower_list public_content likes relationships comments basic')
  end

  def callback
    response = Instagram.get_access_token(params[:code], redirect_uri: CALLBACK_URL)
     if InstagramAuthorization.build.call(response, current_user)
       flash[:notice] = 'authorization'
       # UserM.email(current_user).deliver_now
       redirect_to current_user
     else
       flash[:alert] = 'Authorization falure'
       redirect_to home_path
     end
  end

  def un_follow
    InstagramUnFollow.build.call(current_user, @client, @id)
    flash[:notice] = 'unfollowed success'
    redirect_to :back
  end

  def follow
    InstagramFollow.build.call(current_user, @client, @id)
    redirect_to :back
  end

  private

  def take_data
    @id = params[:id]
    @client = Instagram.client(access_token: current_user.inst_token.access_token)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include Pundit
  
  after_action :verify_authorized
  before_action :find_user
  before_action :info, only: :show
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def show
    @user = current_user.insta_user
    authorize @user_p
    begin
      UpdateRelation.build.call(@client, @user)
      inst = @client.user_recent_media(@user.ins_id)
      TakeTagFromPhotos.build.call(inst, @user)
      @foll = @user.was_followers
      @usr_foll = @user.followers

    rescue Instagram::BadRequest
      flash[:denger] = 'Pleas auth again'
      current_user.update_attributes(have_authorization: false)
      current_user.inst_token.destroy
      redirect_to home_path
    end

  end

  def index
   @user_list = User.active_user
   authorize User
  end

  def not_follow_back
   authorize @user_p
   render_json(@user_p.insta_user.followering - @user_p.insta_user.followers)
  end
  
  def stop_follow
    authorize @user_p
    render_json(@user_p.insta_user.was_followers)
  end

  def pokemon
    authorize @user_p
    render_json(@user_p.insta_user.followers - @user_p.insta_user.followering)
  end

  def info
    begin 
      @client = Instagram.client(access_token:
                                         @user_p.inst_token.access_token)
    rescue
      flash[:alert] = 'You haven\'t got auth'
      redirect_to home_path
    end
  end

  def user_not_authorized
    flash[:alert] = 'You are not cool enough to do this
     - go back from whence you came.'
    redirect_to current_user
  end
  
  def tags
    @user = User.find(params[:id])
    authorize @user
    tags = @user.insta_user.tag_relations.order('counter desc').limit(10)
    @tag = tags.map { |content| 
        { counter: content.counter, name: content.inst_tag.name } }
  end

  private
  
  def find_user
    @user_p = User.find(params[:id])
  end

  def render_json data

    render json: data.map { |content|
              { id: content.ins_id, name: content.username } }
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/insta_tags_helper.rb
module InstaTagsHelper
end

app/views/home/index.html.haml
.invitation
  .container
    .row
      .col-md-1
      .col-md-3
        %p  Wellcome
    .row
      .col-md-2
      .col-md-8
        %p we woudl like to help you

    .row
      .col-md-3
      .col-md-8
        = link_to "autoryzuj", auth_path

app/views/insta_tags/apriori.html.haml
.container
  %p #{@list}
  %p #{@res}

app/views/insta_tags/user_tags.html.haml
.container
  - @tags.each do |d|
    %p #{d.name} #{d.media_count}

app/views/layouts/_footer.html.haml
.foother
   .container
      .nav.navbar.navbar-default.navbar-fixed-bottom

app/views/layouts/_nav.html.haml
.container
  .nav.navbar.navbar-default.navbar-fixed-top
    .container
      %p.navbar-text.nabar-left.logo Inst
      %ul.nav.nav-pills.navbar-right
        - if user_signed_in?
          %li.disable{role: "presentation"}
            =link_to current_user.email, current_user
          %li.disable{role: "presentation"}
            =link_to "Logout", destroy_user_session_path, method: :delete
        - else
          %li.disable{role: "presentation"}
            =link_to "Log in", new_user_session_path
          %li.disable{role: "presentation"}
            =link_to "Sing up", new_registration_path(resource_name)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Insta</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar">
<%= render 'layouts/nav' %>
</div>

<div class= "messages" >
<% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: "alert alert-info" %>
<% end %>
</div>

<div class = "yield-part">
<%= yield %>
</div>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/user_m/email.text.erb
<!DOCTYPE html>
<html>
<head>
  <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
</head>
<body>
<h1>Welcome InB, <%= @user.email %></h1>
<p>
  Thank you for authorization
</p>
<p>
  To login to the site, just follow this link: <%= @url %>.
</p>
<p>Thanks for joining and have a great day!</p>
</body>
</html>

app/views/users/_table.html.haml
.container
  .follow-container
    .row
      .col-md-6
        .panel.panel-default
          .panel-heading
            %p Stop Follow
          %table
            %thead
              %tr
                %td User
                %td Follow from
                %td
            %tbody
              - unless @foll.nil?
                - @foll.each do |f|
                  %tr
                    %td= f.username
                    %td= distance_of_time_in_words(Time.now - f.created_at)
                    %td
                      .button-group

      .col-md-6
        .panel.panel-default
          .panel-heading
            %p Only Followed by
          %table
            %thead
              %tr
                %td User
                %td Follow from
                %td
            %tbody
              - unless @foed.nil?
                - @foed.each do |f|
                  %tr
                    %td= f.username
                    %td= distance_of_time_in_words(Time.now - f.updated_at)
                    %td
                      .button-group
                        = link_to "like photos", "#",
                          method: :post, :class => "btn btn-primary"

app/views/users/_table_jquery.html.erb
<div class="container follow-container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
  <div class="panel panel-default">
    <div class="panel-heading type-table">
      <p>User not follow back</p>
    </div>
    <table id="inst-table">

        <thead>
            <tr>
                <td> Num </td>
                <td> Name </td>
                <td>  </td>

            </tr>
        </thead>
        <tbody class="table-body">

        </tbody>

    </table>
  </div>
  </div>
  </div>
</div>

app/views/users/index.html.haml
.container
  %ul
    - @user_list.each  do |user|
      %li
        #{user.email}
        =link_to "Profil", user_path(user)

app/views/users/show.html.haml
.container
  .row
    .col-md-3.col-md-offset-2
      = image_tag(@user.profile_picture, :class => "img-circle")

    .col-md-7
      %h3 #{@user.username}

      %p
        = link_to "edit" , "#"
        %button.bmanu
          more

      %p.manu.display
        %button.pokemon
          Pokenon
        %button.not_follow_back
          Not follow back
        %button.stop_follow
          Stop follow

      %p
        follower by: #{@user.followers.count}
        followers: #{@user.followering.count}



  =render "users/table_jquery"

app/views/users/tags.html.haml
.container
  %h1
    =@tag